
import React from 'react';
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { CheckCircle, XCircle, Loader2, Mail, User, RefreshCw, Lightbulb } from 'lucide-react';
import { Button } from "@/components/ui/button";
import { TenantFormData } from '@/types/tenant';
import { useSlugGenerator } from '@/hooks/useSlugGenerator';

interface TenantFormBasicProps {
  formData: TenantFormData;
  onFieldChange: (field: keyof TenantFormData, value: string | number) => void;
  currentTenantId?: string;
}

export const TenantFormBasic: React.FC<TenantFormBasicProps> = ({
  formData,
  onFieldChange,
  currentTenantId
}) => {
  const {
    slug,
    setSlug,
    isSlugValid,
    isSlugChecking,
    slugError,
    isAutoGenerated,
    suggestions,
    regenerateSlug,
    useSuggestion
  } = useSlugGenerator(formData.name || '', currentTenantId);

  // Sync slug with form data
  React.useEffect(() => {
    if (slug !== formData.slug) {
      onFieldChange('slug', slug);
    }
  }, [slug, formData.slug, onFieldChange]);

  const getSlugValidationIcon = () => {
    if (!slug) return null;
    if (isSlugChecking) return <Loader2 className="w-4 h-4 animate-spin text-gray-500" />;
    if (isSlugValid) return <CheckCircle className="w-4 h-4 text-green-500" />;
    return <XCircle className="w-4 h-4 text-red-500" />;
  };

  const getSubdomainValidationIcon = () => {
    if (!formData.subdomain) return null;
    const isSubdomainValid = /^[a-z0-9-]+$/.test(formData.subdomain) && 
                            !formData.subdomain.startsWith('-') && 
                            !formData.subdomain.endsWith('-');
    return isSubdomainValid ? 
      <CheckCircle className="w-4 h-4 text-green-500" /> : 
      <XCircle className="w-4 h-4 text-red-500" />;
  };

  const validateEmail = (email: string) => {
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return emailRegex.test(email);
  };

  const getEmailValidationIcon = () => {
    if (!formData.owner_email) return null;
    return validateEmail(formData.owner_email) ? 
      <CheckCircle className="w-4 h-4 text-green-500" /> : 
      <XCircle className="w-4 h-4 text-red-500" />;
  };

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>Organization Details</CardTitle>
          <CardDescription>Basic information about the tenant organization</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="name">Organization Name *</Label>
              <Input
                id="name"
                value={formData.name || ''}
                onChange={(e) => onFieldChange('name', e.target.value)}
                placeholder="Enter organization name"
                required
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="slug" className="flex items-center gap-2">
                Slug *
                {isAutoGenerated && (
                  <span className="text-xs text-green-600 bg-green-50 px-2 py-1 rounded">Auto-generated</span>
                )}
              </Label>
              <div className="relative">
                <Input
                  id="slug"
                  value={slug}
                  onChange={(e) => setSlug(e.target.value.toLowerCase())}
                  placeholder="organization-slug"
                  required
                  className={`pr-20 ${
                    slugError ? 'border-red-500' : 
                    isSlugValid ? 'border-green-500' : ''
                  }`}
                />
                <div className="absolute right-3 top-1/2 transform -translate-y-1/2 flex items-center gap-1">
                  {getSlugValidationIcon()}
                  <Button
                    type="button"
                    variant="ghost"
                    size="sm"
                    onClick={regenerateSlug}
                    className="h-6 w-6 p-0 hover:bg-gray-100"
                    title="Regenerate slug"
                  >
                    <RefreshCw className="w-3 h-3" />
                  </Button>
                </div>
              </div>
              {slugError && (
                <div className="space-y-2">
                  <p className="text-sm text-red-500">{slugError}</p>
                  {suggestions.length > 0 && (
                    <div className="bg-amber-50 border border-amber-200 rounded-lg p-3">
                      <div className="flex items-center gap-2 mb-2">
                        <Lightbulb className="w-4 h-4 text-amber-600" />
                        <span className="text-sm font-medium text-amber-800">Suggested alternatives:</span>
                      </div>
                      <div className="flex flex-wrap gap-2">
                        {suggestions.slice(0, 3).map((suggestion) => (
                          <Button
                            key={suggestion}
                            type="button"
                            variant="outline"
                            size="sm"
                            onClick={() => useSuggestion(suggestion)}
                            className="text-xs h-7"
                          >
                            {suggestion}
                          </Button>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              )}
              {isSlugValid && (
                <p className="text-sm text-green-500">Slug is available</p>
              )}
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="type">Organization Type *</Label>
              <Select value={formData.type || ''} onValueChange={(value) => onFieldChange('type', value)}>
                <SelectTrigger>
                  <SelectValue placeholder="Select organization type" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="agri_company">Agriculture Company</SelectItem>
                  <SelectItem value="dealer">Dealer</SelectItem>
                  <SelectItem value="ngo">NGO</SelectItem>
                  <SelectItem value="government">Government</SelectItem>
                  <SelectItem value="university">University</SelectItem>
                  <SelectItem value="sugar_factory">Sugar Factory</SelectItem>
                  <SelectItem value="cooperative">Cooperative</SelectItem>
                  <SelectItem value="insurance">Insurance</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="subscription_plan">Subscription Plan *</Label>
              <Select value={formData.subscription_plan || ''} onValueChange={(value) => onFieldChange('subscription_plan', value)}>
                <SelectTrigger>
                  <SelectValue placeholder="Select subscription plan" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="Kisan_Basic">Kisan – Starter</SelectItem>
                  <SelectItem value="Shakti_Growth">Shakti – Growth</SelectItem>
                  <SelectItem value="AI_Enterprise">AI – Enterprise</SelectItem>
                  <SelectItem value="custom">Custom Plan</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="status">Status</Label>
              <Select value={formData.status || 'trial'} onValueChange={(value) => onFieldChange('status', value)}>
                <SelectTrigger>
                  <SelectValue placeholder="Select status" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="trial">Trial</SelectItem>
                  <SelectItem value="active">Active</SelectItem>
                  <SelectItem value="suspended">Suspended</SelectItem>
                  <SelectItem value="cancelled">Cancelled</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="subdomain">Subdomain *</Label>
              <div className="relative">
                <Input
                  id="subdomain"
                  value={formData.subdomain || ''}
                  onChange={(e) => onFieldChange('subdomain', e.target.value.toLowerCase())}
                  placeholder="mycompany"
                  required
                  className="pr-10"
                />
                <div className="absolute right-3 top-1/2 transform -translate-y-1/2">
                  {getSubdomainValidationIcon()}
                </div>
              </div>
              <p className="text-sm text-gray-500">
                {formData.subdomain && `https://${formData.subdomain}.yourdomain.com`}
              </p>
            </div>
          </div>
        </CardContent>
      </Card>

      <Card className="border-blue-200 bg-blue-50/50">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <User className="w-5 h-5 text-blue-600" />
            Administrator Account Setup
          </CardTitle>
          <CardDescription>
            These details will be used to create the tenant admin account. 
            <strong className="text-blue-700">A welcome email with login credentials will be sent automatically.</strong>
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="owner_name" className="flex items-center gap-1">
                <User className="w-4 h-4" />
                Administrator Name *
              </Label>
              <Input
                id="owner_name"
                value={formData.owner_name || ''}
                onChange={(e) => onFieldChange('owner_name', e.target.value)}
                placeholder="Enter administrator full name"
                required
              />
              <p className="text-xs text-muted-foreground">This person will be the primary tenant administrator</p>
            </div>
            <div className="space-y-2">
              <Label htmlFor="owner_email" className="flex items-center gap-1">
                <Mail className="w-4 h-4" />
                Administrator Email *
              </Label>
              <div className="relative">
                <Input
                  id="owner_email"
                  type="email"
                  value={formData.owner_email || ''}
                  onChange={(e) => onFieldChange('owner_email', e.target.value)}
                  placeholder="admin@example.com"
                  required
                  className={`pr-10 ${
                    formData.owner_email && !validateEmail(formData.owner_email) ? 'border-red-500' : ''
                  }`}
                />
                <div className="absolute right-3 top-1/2 transform -translate-y-1/2">
                  {getEmailValidationIcon()}
                </div>
              </div>
              {formData.owner_email && !validateEmail(formData.owner_email) && (
                <p className="text-sm text-red-500">Please enter a valid email address</p>
              )}
              <p className="text-xs text-muted-foreground">Welcome email with login credentials will be sent here</p>
            </div>
          </div>
          <div className="space-y-2">
            <Label htmlFor="owner_phone">Administrator Phone (Optional)</Label>
            <Input
              id="owner_phone"
              type="tel"
              value={formData.owner_phone || ''}
              onChange={(e) => onFieldChange('owner_phone', e.target.value)}
              placeholder="+1 (555) 123-4567"
            />
          </div>

          <div className="bg-blue-100 border border-blue-200 rounded-lg p-3">
            <div className="flex items-start gap-2">
              <Mail className="w-5 h-5 text-blue-600 mt-0.5" />
              <div>
                <h4 className="font-medium text-blue-900">Email Notification Process</h4>
                <p className="text-sm text-blue-700 mt-1">
                  After tenant creation, we'll automatically:
                </p>
                <ul className="text-sm text-blue-700 mt-2 space-y-1 pl-4">
                  <li>• Check if the email already has an account</li>
                  <li>• Create a secure admin account (if needed)</li>
                  <li>• Generate temporary login credentials (for new accounts)</li>
                  <li>• Send a branded welcome email with login instructions</li>
                  <li>• Provide password reset options for first-time access</li>
                </ul>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};
